# Generated by Django 4.2.19 on 2025-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
