# Generated by Django 4.2.19 on 2025-03-30 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0003_agent_is_public_agentpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentpermission',
            unique_together={('agent', 'user')},
        ),
        migrations.AlterField(
            model_name='agentpermission',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='agents.agent'),
        ),
        migrations.RemoveField(
            model_name='agentpermission',
            name='organization',
        ),
    ]
