# Generated by Django 4.2.19 on 2025-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='agent',
        ),
    ]
