# Generated by Django 4.2.19 on 2025-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='metadata',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
