# Generated by Django 4.2.19 on 2025-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding_text',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='metadata_text',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
