# Generated by Django 4.2.19 on 2025-03-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('documents', '0005_remove_documentchunk_embedding_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_documents', to='agents.agent'),
        ),
    ]
