# Generated by Django 4.2.19 on 2025-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='agent',
        ),
    ]
